[project]
name = "ort-utils"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.2.6",
    "onnxruntime>=1.22.0",
    "scikit-learn>=1.6.1",
    "skl2onnx>=1.18.0",
]
